import { text, type Spec } from './evolving';

const starter = "import React, { useState } from 'react';\nexport default function App() {\n  return <main />;\n}\n";
export const REACT_EVOLVING: Record<string, Spec> = {
  'react-evolving-board': {
    starter, focus: ['useState', 'filter'],
    prompts: [
      text('Build a task board in default-exported App. Start with no tasks. Provide an input labelled "Task" and button "Add". Trim added text; reject empty text, clear the input after adding. Render each task in an li with a checkbox labelled by its text; toggling changes completion. Duplicate text is allowed and tasks remain independent.', 'Vytvoř nástěnku v komponentě App s default exportem. Začni bez úkolů. Přidej vstup s popiskem "Task" a tlačítko "Add". Text ořízni; prázdný odmítni, po přidání vstup vymaž. Každý úkol vykresli jako li s checkboxem označeným jeho textem; přepnutí mění dokončení. Duplicitní text je povolen a úkoly jsou nezávislé.'),
      text('Add filter buttons "All", "Active", "Completed". Filtering never changes tasks. Each li gains a button named "Delete TASK_TEXT". Show the number of unfinished tasks in an output labelled "Remaining", regardless of the active filter.', 'Přidej filtry "All", "Active", "Completed". Filtr nemění úkoly. Každé li má tlačítko "Delete TEXT_ÚKOLU". V output označeném "Remaining" zobraz počet nedokončených úkolů bez ohledu na filtr.'),
      text('Add "Undo" and "Redo" for adds, deletes and toggles. Track complete immutable task snapshots. New mutations clear redo; filtering does not enter history. Disable unavailable history actions. Preserve the active filter through undo/redo, and restore IDs and completion states so duplicate labels still work independently.', 'Přidej "Undo" a "Redo" pro přidání, smazání a přepnutí. Ukládej celé neměnné snímky úkolů. Nová změna smaže redo; filtr nepatří do historie. Nedostupné akce zakaž. Při undo/redo zachovej filtr a obnov ID i dokončení, aby stejné popisky zůstaly nezávislé.'),
    ],
    hints: [text('Give tasks stable IDs rather than using their text as identity.', 'Dej úkolům stabilní ID místo použití textu jako identity.'), text('Derive visible tasks and remaining count from the full task list.', 'Viditelné úkoly a zbývající počet odvozuj z celého seznamu.'), text('Store past, present and future together and update them atomically.', 'Ulož minulost, přítomnost a budoucnost společně a měň je atomicky.')],
    suites: [
      `const add=(name)=>{fireEvent.change(screen.getByLabelText('Task'),{target:{value:name}});fireEvent.click(screen.getByRole('button',{name:'Add',exact:true}))};
test('add, trim, reject blank and independently toggle duplicates',()=>{render(<App/>);add('   ');expect(screen.queryAllByRole('checkbox').length).toBe(0);add(' Write ');add('Write');const boxes=screen.getAllByRole('checkbox',{name:'Write'});expect(boxes.length).toBe(2);expect(screen.getByLabelText('Task').value).toBe('');fireEvent.click(boxes[0]);expect(boxes[0].checked).toBe(true);expect(boxes[1].checked).toBe(false)});`,
      `test('filter, delete and derive remaining count',()=>{render(<App/>);add('One');add('Two');fireEvent.click(screen.getByRole('checkbox',{name:'One'}));fireEvent.click(screen.getByRole('button',{name:'Active',exact:true}));expect(screen.queryByRole('checkbox',{name:'One'})).toBeNull();expect(screen.getByLabelText('Remaining').textContent).toBe('1');fireEvent.click(screen.getByRole('button',{name:'Delete Two',exact:true}));expect(screen.getByLabelText('Remaining').textContent).toBe('0');fireEvent.click(screen.getByRole('button',{name:'Completed',exact:true}));expect(screen.getByRole('checkbox',{name:'One'}).checked).toBe(true)});`,
      `test('history restores tasks and keeps filters; divergent edits clear redo',()=>{render(<App/>);const undo=screen.getByRole('button',{name:'Undo',exact:true}),redo=screen.getByRole('button',{name:'Redo',exact:true});expect(undo.disabled).toBe(true);expect(redo.disabled).toBe(true);add('One');fireEvent.click(screen.getByRole('checkbox',{name:'One'}));fireEvent.click(screen.getByRole('button',{name:'Completed',exact:true}));fireEvent.click(undo);expect(screen.queryByRole('checkbox',{name:'One'})).toBeNull();fireEvent.click(redo);expect(screen.getByRole('checkbox',{name:'One'}).checked).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Delete One',exact:true}));fireEvent.click(undo);expect(screen.getByRole('checkbox',{name:'One'}).checked).toBe(true);add('Two');expect(redo.disabled).toBe(true)});`,
    ],
  },
  'react-evolving-catalog': {
    starter, focus: ['useState', 'filter', 'sort'],
    prompts: [
      text('Build App with products: {id:1,name:"Apple",price:2}, {id:2,name:"Banana",price:1}, {id:3,name:"Carrot",price:3}, {id:4,name:"Dates",price:4}. Render each product as an li containing its name and price. Provide a "Search" input: case-insensitive, trimmed substring matching by name. No matches shows "No products".', 'Vytvoř App s produkty: {id:1,name:"Apple",price:2}, {id:2,name:"Banana",price:1}, {id:3,name:"Carrot",price:3}, {id:4,name:"Dates",price:4}. Každý produkt vykresli jako li s názvem a cenou. Vstup "Search" filtruje podle části názvu bez ohledu na velikost písmen a krajní mezery. Při prázdném výsledku zobraz "No products".'),
      text('Add a select labelled "Sort" with values "name", "price-asc", "price-desc" (default name). Paginate the filtered, sorted result, two products per page. Buttons "Previous" and "Next" are disabled at boundaries. output "Page" shows "1 / 2" etc.; empty results show "0 / 0". Reset to the first page whenever search or sort changes.', 'Přidej select "Sort" s hodnotami "name", "price-asc", "price-desc" (výchozí name). Filtrované seřazené výsledky stránkuj po dvou. "Previous" a "Next" jsou na hranicích zakázané. output "Page" ukazuje "1 / 2" apod.; prázdný výsledek "0 / 0". Při změně hledání nebo řazení se vrať na první stránku.'),
      text('Add a checkbox labelled with the product name in each li. Selection survives paging, searching and sorting. output "Selected total" shows the sum of prices of ALL selected products, including hidden ones. "Select page" selects every visible item, never toggles existing selections; disable it on an empty page. "Clear selection" clears all and is disabled when empty.', 'Do každého li přidej checkbox s názvem produktu. Výběr přetrvá při stránkování, hledání i řazení. output "Selected total" ukazuje součet cen VŠECH vybraných produktů, včetně skrytých. "Select page" vybere vše viditelné, již vybrané nepřepíná; na prázdné stránce je zakázané. "Clear selection" vymaže vše a bez výběru je zakázané.'),
    ],
    hints: [text('Derive results during render instead of keeping a second synchronized list.', 'Výsledky odvozuj při renderování místo ukládání druhého synchronizovaného seznamu.'), text('Filter, sort a copy, then slice. Change query and page together.', 'Filtruj, seřaď kopii a pak použij slice. Dotaz a stránku měň společně.'), text('Keep selected IDs separate from visible rows; total uses the full catalog.', 'Vybraná ID drž odděleně od viditelných řádků; součet vychází z celého katalogu.')],
    suites: [
      `const search=value=>fireEvent.change(screen.getByLabelText('Search'),{target:{value}});
test('search is trimmed and case-insensitive and handles no results',()=>{render(<App/>);search(' APP ');expect(screen.getAllByRole('listitem').length).toBe(1);expect(screen.getByRole('listitem').textContent).toContain('Apple');search('xyz');expect(screen.getByText('No products')).toBeTruthy();search('banana');expect(screen.getByRole('listitem').textContent).toContain('1')});`,
      `test('sort, paginate, clamp empty pages and reset on search',()=>{render(<App/>);expect(screen.getAllByRole('listitem').length).toBe(2);expect(screen.getByRole('button',{name:'Previous',exact:true}).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Sort'),{target:{value:'price-desc'}});expect(screen.getAllByRole('listitem')[0].textContent).toContain('Dates');fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));expect(screen.getByLabelText('Page').textContent).toBe('2 / 2');expect(screen.getByRole('button',{name:'Next',exact:true}).disabled).toBe(true);search('apple');expect(screen.getByLabelText('Page').textContent).toBe('1 / 1');search('zzz');expect(screen.getByLabelText('Page').textContent).toBe('0 / 0')});`,
      `test('selection survives hidden pages and select-page is idempotent',()=>{render(<App/>);const clear=screen.getByRole('button',{name:'Clear selection',exact:true});expect(clear.disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Select page',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Select page',exact:true}));expect(screen.getByLabelText('Selected total').textContent).toBe('3');fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));fireEvent.click(screen.getByRole('checkbox',{name:'Dates'}));expect(screen.getByLabelText('Selected total').textContent).toBe('7');search('zzz');expect(screen.getByRole('button',{name:'Select page',exact:true}).disabled).toBe(true);expect(screen.getByLabelText('Selected total').textContent).toBe('7');fireEvent.click(clear);expect(screen.getByLabelText('Selected total').textContent).toBe('0')});`,
    ],
  },
  'react-evolving-form': {
    starter, focus: ['useState', 'forms'],
    prompts: [
      text('Build App with a form containing an "Email" input and "Next" button. Trim email and validate with /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/. Invalid submission shows role=alert text "Invalid email" and remains editable. A valid submission displays "Email accepted". Never reload the page.', 'Vytvoř App s formulářem: vstup "Email" a tlačítko "Next". Email ořízni a validuj pomocí /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/. Neplatné odeslání zobrazí role=alert s "Invalid email" a umožní opravu. Platné odeslání zobrazí "Email accepted". Nenačítej stránku znovu.'),
      text('After email acceptance open a second step, keeping "Email accepted" visible. Provide "Name" input and "Back" / "Next" buttons. Name must contain at least two non-whitespace characters after trimming, otherwise show alert "Invalid name". Valid submission opens a summary showing the trimmed email and name. Back navigation from step 2 and summary preserves both fields.', 'Po přijetí emailu otevři druhý krok a zachovej "Email accepted". Přidej vstup "Name" a "Back" / "Next". Jméno musí po oříznutí obsahovat alespoň dva neprázdné znaky, jinak zobraz alert "Invalid name". Platné odeslání otevře souhrn s oříznutým emailem a jménem. Back z druhého kroku i souhrnu zachová obě pole.'),
      text('On the summary add a checkbox labelled "I agree" and "Submit" button, disabled until agreed. Submit freezes a snapshot of email/name and shows "Submitted" plus the snapshot, with no editable fields or Submit button. Add "Start over" only after submission: reset all fields, consent, errors and step. Going Back before submission clears consent, preventing acceptance of an edited summary.', 'Do souhrnu přidej checkbox "I agree" a "Submit", zakázané bez souhlasu. Submit zmrazí snímek emailu/jména a ukáže "Submitted" i snímek, bez editovatelných polí a tlačítka Submit. Po odeslání přidej "Start over": vymaže pole, souhlas, chyby i krok. Back před odesláním ruší souhlas, aby změněný souhrn nebyl automaticky schválen.'),
    ],
    hints: [text('Use a submit handler with preventDefault and explicit validation.', 'Použij submit handler s preventDefault a explicitní validací.'), text('Keep field state above the conditional step UI.', 'Drž stav polí nad podmíněně vykreslovanými kroky.'), text('Represent submitted as a terminal state with its own snapshot.', 'Modeluj odeslání jako konečný stav s vlastním snímkem.')],
    suites: [
      `const fill=(label,value)=>fireEvent.change(screen.getByLabelText(label),{target:{value}});const next=()=>fireEvent.click(screen.getByRole('button',{name:'Next',exact:true}));
test('validate email without losing the form',()=>{render(<App/>);fill('Email','bad');next();expect(screen.getByRole('alert').textContent).toBe('Invalid email');fill('Email',' ada@example.com ');next();expect(screen.getByText('Email accepted')).toBeTruthy()});`,
      `test('validate name and preserve fields through back navigation',()=>{render(<App/>);fill('Email','ada@example.com');next();fill('Name',' A ');next();expect(screen.getByRole('alert').textContent).toBe('Invalid name');fill('Name',' Ada ');next();expect(screen.getByText('Ada')).toBeTruthy();expect(screen.getByText('ada@example.com')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Back',exact:true}));expect(screen.getByLabelText('Name').value.trim()).toBe('Ada');fireEvent.click(screen.getByRole('button',{name:'Back',exact:true}));expect(screen.getByLabelText('Email').value).toBe('ada@example.com')});`,
      `test('consent, terminal submission and clean restart',()=>{render(<App/>);fill('Email','ada@example.com');next();fill('Name','Ada');next();expect(screen.getByRole('button',{name:'Submit',exact:true}).disabled).toBe(true);fireEvent.click(screen.getByLabelText('I agree'));fireEvent.click(screen.getByRole('button',{name:'Back',exact:true}));next();expect(screen.getByLabelText('I agree').checked).toBe(false);fireEvent.click(screen.getByLabelText('I agree'));fireEvent.click(screen.getByRole('button',{name:'Submit',exact:true}));expect(screen.getByText('Submitted')).toBeTruthy();expect(screen.queryByRole('button',{name:'Submit',exact:true})).toBeNull();expect(screen.getByText('ada@example.com')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Start over',exact:true}));expect(screen.getByLabelText('Email').value).toBe('');expect(screen.queryByRole('alert')).toBeNull()});`,
    ],
  },
};
